#!/bin/bash
#set -o xtrace

targetSizeMegabytes=$2
fileInput=$1
ext="${fileInput##*.}"; 
fileOutput="${fileInput}.shrunk.${ext}"
durationSeconds=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 $fileInput)
bitrate=$(( $(echo "scale=0; ($targetSizeMegabytes*1024)/$durationSeconds" | bc) * 8 ))
#bitrate=$(($targetSizeKilobytes / $durationSeconds))
beforeSizeBytes=$(stat --printf="%s" $fileInput)
echo "Shrinking ${fileInput} to ${targetSizeKilobytes}KB. Bitrate: ${bitrate}k"
ffmpeg \
	-y \
	-hide_banner \
	-loglevel error \
	-i "$fileInput" \
	-b ${bitrate}k \
	-cpu-used 6 \
	-c:a copy \
	$fileOutput
afterSizeBytes=$(stat --printf="%s" $fileOutput)
shrinkPercentage=$(($beforeSizeBytes / $afterSizeBytes))
echo "Rebuilt file as ${fileOutput}, shrank to ${shrinkPercentage}% of original size"
